### ISSUE TITLE
Do i have to apply a clientId 

### ISSUE THREAD

**Issue by hiit-tabata** [williamkapke/amazon-drive#1]
Amazon just block rclone in recent days, I want to build a upload client by my own. 
I want to ask what is the work flow if i want to upload file through the script. 
I saw it require a auth.json for OAuth, what is the format of auth.json 

Thank you

**Comment by williamkapke** [comment]
It looks like this:
```js
{
  "access_token": "Atza|<...very...long...token>",
  "refresh_token": "Atzr|<...very...long...token>",
  "token_type": "bearer",
  "expires_in": 3600
}
```
...this is the json that is returned when you authenticate here:
https://data-mind-687.appspot.com

As you probably noticed- I'm JUST building this now- sorry for the lack of docs right now. So.. thanks for checking it out and asking questions 👍

**Comment by hiit-tabata** [comment]
Thank you
